---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-prod
  namespace: prod
  labels:
    app: test-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-prod
  template:
    metadata:
      labels:
        app: test-prod
    spec:
      containers:
      - name: test-prod
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080