---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-qa
  namespace: qa
  labels:
    app: test-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-qa
  template:
    metadata:
      labels:
        app: test-qa
    spec:
      containers:
      - name: test-qa
        image: ${IMAGE}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080